-- 004_create_resources.sql
CREATE TABLE IF NOT EXISTS resources (
    id                    INT UNSIGNED    NOT NULL AUTO_INCREMENT,
    isbn_13               CHAR(13)        NULL,
    title                 VARCHAR(300)    NOT NULL,
    authors               JSON            NOT NULL,
    publisher             VARCHAR(200)    NULL,
    publication_year      SMALLINT        NULL,
    category_id           INT UNSIGNED    NOT NULL,
    branch_id             INT UNSIGNED    NULL,
    support_type             ENUM('physical','digital') NOT NULL DEFAULT 'physical',
    description           TEXT            NULL,
    pages                 SMALLINT UNSIGNED NULL,
    language              CHAR(2)         NOT NULL DEFAULT 'es',
    cover_image           VARCHAR(255)    NULL,
    location              VARCHAR(100)    NULL,
    digital_url           TEXT            NULL,
    acquisition_price     DECIMAL(8,2)    NULL,
    replacement_cost      DECIMAL(8,2)    NOT NULL,
    acquisition_date      DATE            NULL,
    acquired_at           DATETIME        NULL,
    is_new_acquisition    TINYINT(1)      NOT NULL DEFAULT 1,
    total_copies          TINYINT UNSIGNED NOT NULL DEFAULT 0,
    available_copies      TINYINT UNSIGNED NOT NULL DEFAULT 0,
    digital_access_count  INT UNSIGNED    NOT NULL DEFAULT 0,
    is_active             TINYINT(1)      NOT NULL DEFAULT 1,
    deactivated_at        DATETIME        NULL,
    deactivated_by        INT UNSIGNED    NULL,
    deactivation_reason   TEXT            NULL,
    created_at            DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE INDEX uq_resources_isbn (isbn_13),
    CONSTRAINT fk_resources_category FOREIGN KEY (category_id) REFERENCES categories (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_resources_branch FOREIGN KEY (branch_id) REFERENCES library_branches (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_resources_deactivated_by FOREIGN KEY (deactivated_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
    INDEX idx_resources_support_active (support_type, is_active),
    INDEX idx_resources_branch (branch_id, is_active),
    INDEX idx_resources_new_acquisition (is_new_acquisition, acquired_at),
    INDEX idx_resources_category (category_id),
    FULLTEXT INDEX ft_resources (title, publisher, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
